#############################################################################
# Makefile for building: HelloWindow
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  HelloWindow.pro
# Template: app
# Command: /home/wowk/Software/Qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile HelloWindow.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -IGL/include -I/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/wowk/Software/Qt5.8.0/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = HelloWindow1.0.0
DISTDIR = /media/wowk/AA3898E53898B235/Development/OpenGL/HelloWindow/.tmp/HelloWindow1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lGL -lGLU -lSDL2 -ldl 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		GLObject.cpp \
		GLApplication.cpp \
		GL/src/glad.cpp \
		GLShader.cpp \
		Utils/FileUtil.cpp 
OBJECTS       = main.o \
		GLObject.o \
		GLApplication.o \
		glad.o \
		GLShader.o \
		FileUtil.o
DIST          = triangle.frag \
		triangle.vert \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		HelloWindow.pro GL/include/glad/glad.h \
		GLObject.h \
		GLApplication.h \
		GLShader.h \
		GL/include/KHR/khrplatform.h \
		Utils/FileUtil.h main.cpp \
		GLObject.cpp \
		GLApplication.cpp \
		GL/src/glad.cpp \
		GLShader.cpp \
		Utils/FileUtil.cpp
QMAKE_TARGET  = HelloWindow
DESTDIR       = 
TARGET        = HelloWindow


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HelloWindow.pro /home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf /home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		HelloWindow.pro
	$(QMAKE) -o Makefile HelloWindow.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../../Deepin/Software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf:
/home/wowk/Software/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf:
HelloWindow.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile HelloWindow.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp GLApplication.h \
		GLObject.h \
		GL/include/glad/glad.h \
		GL/include/KHR/khrplatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

GLObject.o: GLObject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLObject.o GLObject.cpp

GLApplication.o: GLApplication.cpp GLApplication.h \
		GLObject.h \
		GL/include/glad/glad.h \
		GL/include/KHR/khrplatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLApplication.o GLApplication.cpp

glad.o: GL/src/glad.cpp GL/include/glad/glad.h \
		GL/include/KHR/khrplatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glad.o GL/src/glad.cpp

GLShader.o: GLShader.cpp GLShader.h \
		GL/include/glad/glad.h \
		GL/include/KHR/khrplatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLShader.o GLShader.cpp

FileUtil.o: Utils/FileUtil.cpp Utils/FileUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileUtil.o Utils/FileUtil.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

